### PR TITLE
support laravel 9

### PR DESCRIPTION
**Pull request by mattvb91**
@Gummibeer can you take a look as im missing full context but all the tests pass:

```
  Tests:  27 passed
  Time:   1.65s
```

### CODE REVIEW

**Comment by mattvb91** [comment]
ping @Gummibeer @SarahSibert

**Review by Gummibeer — APPROVED** [review]
thanks 🎉

**Comment by mattvb91** [comment]
> thanks tada

aaah thanks of course both could be added too, i was assuming the tag would be a major bump but this is even better! Thank you

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/laravel-dns/releases/tag/0.2.0

**Pull request merged**
